<?php
/**
 * QR Code widget.
 *
 * PRIVACY NOTE: To avoid bundling a full QR encoder, this widget renders the
 * QR as an <img> from a public QR image service (api.qrserver.com). The encoded
 * value (page URL, guest name, or custom text) is therefore sent to that
 * third-party service by the visitor's browser. Default source is the page URL.
 *
 * @package WeddingWidget
 */

namespace WeddingWidget\Widgets;

use Elementor\Widget_Base;
use Elementor\Controls_Manager;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WW_QR extends Widget_Base {

	public function get_name() {
		return 'ww-qr';
	}

	public function get_title() {
		return esc_html__( 'QR Code', 'wedding-widget' );
	}

	public function get_icon() {
		return 'eicon-barcode';
	}

	public function get_categories() {
		return array( 'wedding-widget' );
	}

	public function get_keywords() {
		return array( 'qr', 'qrcode', 'checkin', 'wedding' );
	}

	public function get_style_depends() {
		return array( 'wedding-widget' );
	}

	protected function register_controls() {
		$this->start_controls_section(
			'section_content',
			array( 'label' => esc_html__( 'QR Code', 'wedding-widget' ) )
		);

		$this->add_control( 'data_source', array(
			'label'   => esc_html__( 'Data Source', 'wedding-widget' ),
			'type'    => Controls_Manager::SELECT,
			'default' => 'page_url',
			'options' => array(
				'page_url'   => esc_html__( 'Current Page URL', 'wedding-widget' ),
				'guest_name' => esc_html__( 'Guest Name (?to=)', 'wedding-widget' ),
				'custom'     => esc_html__( 'Custom Text', 'wedding-widget' ),
			),
		) );

		$this->add_control( 'custom_text', array(
			'label'     => esc_html__( 'Custom Text', 'wedding-widget' ),
			'type'      => Controls_Manager::TEXT,
			'default'   => '',
			'dynamic'   => array( 'active' => true ),
			'condition' => array( 'data_source' => 'custom' ),
		) );

		$this->add_control( 'privacy_note', array(
			'type'            => Controls_Manager::RAW_HTML,
			'raw'             => esc_html__( 'The QR is generated by api.qrserver.com. The encoded value is sent to that external service.', 'wedding-widget' ),
			'content_classes' => 'elementor-panel-alert elementor-panel-alert-warning',
		) );

		$this->add_control( 'size', array(
			'label'   => esc_html__( 'Size (px)', 'wedding-widget' ),
			'type'    => Controls_Manager::NUMBER,
			'default' => 180,
			'min'     => 80,
			'max'     => 600,
		) );

		$this->add_control( 'fg_color', array(
			'label'   => esc_html__( 'Foreground', 'wedding-widget' ),
			'type'    => Controls_Manager::COLOR,
			'default' => '#000000',
		) );

		$this->add_control( 'bg_color', array(
			'label'   => esc_html__( 'Background', 'wedding-widget' ),
			'type'    => Controls_Manager::COLOR,
			'default' => '#ffffff',
		) );

		$this->add_responsive_control( 'align', array(
			'label'     => esc_html__( 'Alignment', 'wedding-widget' ),
			'type'      => Controls_Manager::CHOOSE,
			'options'   => array(
				'flex-start' => array( 'title' => esc_html__( 'Left', 'wedding-widget' ), 'icon' => 'eicon-text-align-left' ),
				'center'     => array( 'title' => esc_html__( 'Center', 'wedding-widget' ), 'icon' => 'eicon-text-align-center' ),
				'flex-end'   => array( 'title' => esc_html__( 'Right', 'wedding-widget' ), 'icon' => 'eicon-text-align-right' ),
			),
			'default'   => 'center',
			'selectors' => array( '{{WRAPPER}} .ww-qr' => 'justify-content: {{VALUE}};' ),
		) );

		$this->end_controls_section();
	}

	/**
	 * Resolve the value to encode based on the chosen source.
	 */
	private function resolve_data( $settings ) {
		switch ( $settings['data_source'] ?? 'page_url' ) {
			case 'guest_name':
				return isset( $_GET['to'] ) ? sanitize_text_field( wp_unslash( $_GET['to'] ) ) : '';
			case 'custom':
				return (string) ( $settings['custom_text'] ?? '' );
			case 'page_url':
			default:
				$scheme = is_ssl() ? 'https' : 'http';
				return esc_url_raw( $scheme . '://' . ( $_SERVER['HTTP_HOST'] ?? '' ) . ( $_SERVER['REQUEST_URI'] ?? '' ) );
		}
	}

	protected function render() {
		$settings = $this->get_settings_for_display();
		$data     = $this->resolve_data( $settings );

		if ( '' === $data ) {
			if ( \Elementor\Plugin::$instance->editor->is_edit_mode() ) {
				echo '<div class="ww-qr__placeholder">' . esc_html__( 'No data to encode yet.', 'wedding-widget' ) . '</div>';
			}
			return;
		}

		$size = absint( $settings['size'] ?? 180 );
		$size = max( 80, min( 600, $size ) );
		$fg   = ltrim( (string) ( $settings['fg_color'] ?? '#000000' ), '#' );
		$bg   = ltrim( (string) ( $settings['bg_color'] ?? '#ffffff' ), '#' );

		$src = add_query_arg(
			array(
				'size'    => $size . 'x' . $size,
				'data'    => rawurlencode( $data ),
				'color'   => $fg,
				'bgcolor' => $bg,
				'margin'  => 0,
			),
			'https://api.qrserver.com/v1/create-qr-code/'
		);
		?>
		<div class="ww-qr">
			<img class="ww-qr__img"
				src="<?php echo esc_url( $src ); ?>"
				width="<?php echo esc_attr( $size ); ?>"
				height="<?php echo esc_attr( $size ); ?>"
				alt="<?php esc_attr_e( 'QR Code', 'wedding-widget' ); ?>"
				loading="lazy">
		</div>
		<?php
	}
}
